# Generated by Django 3.2.8 on 2021-10-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(blank=True, max_length=255)),
                ('url_actual', models.CharField(max_length=4096)),
            ],
        ),
    ]
