# Generated by Django 3.2.8 on 2021-10-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='url_id',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
