# Generated by Django 3.2.8 on 2021-10-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_url_url_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='url_last_click',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
